# NumPy Arrays Basics

## Package Imports

In [2]:
import numpy as np

In [4]:
sales = [0, 5, 155, 0, 518, 0, 1827, 616, 317, 325]
sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

In [5]:
type(sales_array) #NumPy arrays are 'ndarray' Python data type i.e n-dimensional array

numpy.ndarray

### NumPy Array Properties

In [6]:
print(f"ndim : {sales_array.ndim}")
print(f"shape : {sales_array.shape}")
print(f"size : {sales_array.size}")
print(f"dtype : {sales_array.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64


#### Multidimensional array

In [7]:
sales = [[0, 5, 155, 0, 518], [0, 1827, 616, 317, 325]]
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [8]:
print(f"ndim : {sales_array.ndim}")
print(f"shape : {sales_array.shape}")
print(f"size : {sales_array.size}")
print(f"dtype : {sales_array.dtype}")

ndim : 2
shape : (2, 5)
size : 10
dtype : int64


##### Creating array

In [12]:
import numpy as np
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [17]:
array.shape

(5,)

##### Two Dimensional Array

In [15]:
array_2d = np.array([range(5), range(5)])
array_2d


array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [16]:
array_2d.shape  # 2 row, 5 column

(2, 5)

In [18]:
array_2d.size

10

##### Transposing an array

In [21]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

## Assignment 1 - Array Basics
Q. Can you convert a Python list into a NumPy array and help me get familiar with their properties? Once you've done that, report the dimensions, shape, size and dtype

In [22]:
my_list = [x*10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [25]:
my_list_in_numpy = np.array(my_list)
my_list_in_numpy

1

In [26]:
print(f"ndim : {my_list_in_numpy.ndim}")
print(f"shape : {my_list_in_numpy.shape}")
print(f"size : {my_list_in_numpy.size}")
print(f"dtype : {my_list_in_numpy.dtype}")

ndim : 1
shape : (10,)
size : 10
dtype : int64
