In [30]:
import numpy as np

In [31]:
np.ones(4, )

array([1., 1., 1., 1.])

In [32]:
np.zeros((2,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.arange(10) # stop is not inclusive.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1, 15, 2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [35]:
np.linspace(1, 10, 5) # stop is inclusive

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
np.arange(1, 9, 2).reshape(2,2)

array([[1, 3],
       [5, 7]])